Repository codereport/jsource, pull requests merged in 2021-01, with the labels that each got.

#1 Build instructions
  README.md
Labels: documentation

#3 try jeload as lib
  jsrc/CMakeLists.txt
Labels: enhancement

#5 Cleaned Android conditional compilations
  hostdefs/hostdefs.c
  jsrc/andjnative.c
  jsrc/cpuinfo.c
  jsrc/d.c
  jsrc/f.c
  jsrc/io.c
  jsrc/j.h
  jsrc/jconsole.c
  jsrc/jeload.cpp
  jsrc/js.h
  jsrc/jversion-x.h
  jsrc/tsdll.c
  jsrc/vm.c
  jsrc/vz.c
  jsrc/x15.c
  jsrc/xd.c
  jsrc/xf.c
  jsrc/xh.c
  jsrc/xl.c
  jsrc/xsha.c
Labels: enhancement

#7 Removed most WIN32 conditional compilations
  hostdefs/hostdefs.c
  jsrc/aes-arm.c
  jsrc/aes-ni.c
  jsrc/cpuinfo.c
  jsrc/d.c
  jsrc/dtoa.c
  jsrc/io.c
  jsrc/j.h
  jsrc/jconsole.c
  jsrc/jdlllic.c
  jsrc/jeload.cpp
  jsrc/jep.c
  jsrc/jfex.c
  jsrc/js.h
  jsrc/jtype.h
  jsrc/linenoise.c
  jsrc/m.c
  jsrc/m.h
  jsrc/openssl/sha/openssl-util.c
  jsrc/openssl/sha/sha.h
  jsrc/tsdll.c
  jsrc/vcant.c
  jsrc/vf.c
  jsrc/vfrom.c
  jsrc/x.c
  jsrc/x15.c
  jsrc/xa.c
  jsrc/xaes.c
  jsrc/xd.c
  jsrc/xf.c
  jsrc/xfmt.c
  jsrc/xh.c
  jsrc/xl.c
  jsrc/xo.c
  jsrc/xs.c
  jsrc/xt.c
  netdefs/netdefs.c
Labels: enhancement

#8 Removed all WIN32 conditional compilation except ARM
  hostdefs/hostdefs.c
  jsrc/andjnative.c
  jsrc/cpuinfo.c
  jsrc/j.h
  jsrc/jconsole.c
  jsrc/jeload.cpp
  jsrc/m.c
  jsrc/tsdll.c
  jsrc/vfrom.c
  jsrc/vz.c
  jsrc/x.c
  jsrc/x15.c
  jsrc/xf.c
  jsrc/xh.c
Labels: enhancement

#9 Fixed linker errors for macOS
  CONTRIBUTING.md
  jsrc/CMakeLists.txt
  jsrc/blis/gemm_vec-ref.c
  jsrc/jeload.cpp
Labels: bug

#20 Comment out failing tests
  test/CMakeLists.txt
  test/g221.ijs
  test/g300.ijs
  test/g5x30.ijs
  test/g602.ijs
  test/g9x40.ijs
  test/gmmf.ijs
  test/gmmf1s.ijs
  test/gmmf1u.ijs
  test/gmmf1w.ijs
  test/gsco1.ijs
  test/gsco1u.ijs
  test/gu.ijs
  test/gu0.ijs
Labels: ci / build

#17 Small Refactoring: jefail refactored to C++
  jsrc/jconsole.c
  jsrc/jeload.cpp
  jsrc/jeload.h
Labels: c to c++

#29 Temporarily disable `gmmf.ijs`
  test/CMakeLists.txt
Labels: ci / build

#31 Removing 32-bit Support
  base64/lib/arch/generic/32/dec_loop.c
  base64/lib/arch/generic/32/enc_loop.c
  base64/lib/arch/generic/codec-generic.c
  jsrc/a.c
  jsrc/am.c
  jsrc/andjnative.c
  jsrc/ao.c
  jsrc/ar.c
  jsrc/ca.c
  jsrc/cc.c
  jsrc/cip.c
  jsrc/cr.c
  jsrc/f.c
  jsrc/f2.c
  jsrc/j.c
  jsrc/j.h
  jsrc/ja.h
  jsrc/je.h
  jsrc/js.h
  jsrc/jtype.h
  jsrc/k.c
  jsrc/m.c
  jsrc/tsdll.c
  jsrc/u.c
  jsrc/v1.c
  jsrc/v2.c
  jsrc/va.h
  jsrc/va1.c
  jsrc/va2.c
  jsrc/vasm.h
  jsrc/vcant.c
  jsrc/ve.c
  jsrc/vf.c
  jsrc/vfft.c
  jsrc/vfrom.c
  jsrc/vg.c
  jsrc/vgranking.c
  jsrc/vgsort.c
  jsrc/vi.c
  jsrc/vo.c
  jsrc/vrand.c
  jsrc/vu.c
  jsrc/vx.c
  jsrc/vx.h
  jsrc/wn.c
  jsrc/x.c
  jsrc/x15.c
  jsrc/xb.c
  jsrc/xcrc.c
  jsrc/xd.c
  jsrc/xf.c
  jsrc/xfmt.c
Labels: code removal

#32 Removing C_LE (Big Endian support)
  jsrc/ar.c
  jsrc/dtoa.c
  jsrc/j.h
  jsrc/js.h
  jsrc/jtype.h
  jsrc/k.c
  jsrc/sl.c
  jsrc/va2.c
  jsrc/vcompsc.c
  jsrc/ve.c
  jsrc/vg.c
  jsrc/vg.h
  jsrc/vgranking.c
  jsrc/vgsort.c
  jsrc/vi.c
  jsrc/viix.c
  jsrc/vu.c
  jsrc/x15.c
  jsrc/xb.c
Labels: code removal

#33 Removing NODF & ARMHF & WINCE
  cmake/FindOpenMP.cmake
  jsrc/CMakeLists.txt
  jsrc/aes-arm.c
  jsrc/d.c
  jsrc/io.c
  jsrc/j.h
  jsrc/jconsole.c
  jsrc/jdlllic.c
  jsrc/jfex.c
  jsrc/js.h
  jsrc/jt.h
  jsrc/jversion.h
  jsrc/rl.c
  jsrc/va.h
  jsrc/x.c
  jsrc/x.h
  jsrc/x15.c
  jsrc/xa.c
  jsrc/xd.c
  jsrc/xf.c
  jsrc/xh.c
  jsrc/xl.c
  jsrc/xo.c
  jsrc/xt.c
Labels: code removal

#35 Adding initial clang-format config
  .clang-format
Labels: code quality

#34 Fixing `E.` jebar unit tests
  jsrc/CMakeLists.txt
  jsrc/j.h
  jsrc/vb.c
  test/CMakeLists.txt
  test/g5x30.ijs
  test/g602.ijs
  test/g9x40.ijs
  test/gmmf.ijs
  test/gmmf1s.ijs
  test/gmmf1u.ijs
  test/gmmf1w.ijs
  test/gu.ijs
  test/gu0.ijs
Labels: c to c++, ci / build, fix

#23 Removing remaining SLEEF related code
  jsrc/ca.c
  jsrc/j.c
  jsrc/vm.c
Labels: code removal

#36 Removing /benchmarks
  benchmark/avx.ijs
Labels: code removal

#11 Centered-title-and-badges-in README.md
  README.md
Labels: enhancement

#38 remove clion's build and settings via .gitignore
  .gitignore
Labels: ci / build

#40 Remove .h files from target sources in CMakeLists.txt. Replaced with target_include_directories.
  jsrc/CMakeLists.txt
Labels: ci / build

#44 Random code removals
  jsrc/CMakeLists.txt
  jsrc/aes-ni.c
  jsrc/andjnative.c
  jsrc/ao.c
  jsrc/blis.h
  jsrc/cip.c
  jsrc/cipfloatmm_t.h
  jsrc/codingrules.txt
  jsrc/com_jsoftware_j_JInterface.h
  jsrc/cpuinfo.c
  jsrc/cpuinfo.h
  jsrc/crc32c.c
  jsrc/crc32c.h
  jsrc/dtoa.c
  jsrc/f2.c
  jsrc/gemm.c
  jsrc/i.c
  jsrc/j.h
  jsrc/jconsole.c
  jsrc/je.h
  jsrc/js.h
  jsrc/jt.h
  jsrc/jtype.h
  jsrc/linenoise.c
  jsrc/m.c
  jsrc/m.h
  jsrc/v1.c
  jsrc/va.h
  jsrc/vb.c
  jsrc/x.c
  jsrc/x15.c
  jsrc/xa.c
  jsrc/xaes.c
  jsrc/xb.c
  jsrc/xd.c
  jsrc/xf.c
  jsrc/xh.c
  jsrc/xl.c
  jsrc/xo.c
  jsrc/xs.c
  jsrc/xsha.c
  jsrc/xt.c
Labels: code removal

#25 Jeload.cpp refactoring
  jsrc/CMakeLists.txt
  jsrc/jeload.cpp
  jsrc/jeload.h
  jsrc/util/string.cpp
  jsrc/util/string.hpp
Labels: c to c++, code quality

#46 Remove MEMAUDIT
  jsrc/adverbs/ao.c
  jsrc/conjunctions/cg.c
  jsrc/j.h
  jsrc/ja.h
  jsrc/je.h
  jsrc/jt.h
  jsrc/m.c
  jsrc/p.c
  jsrc/xa.c
Labels: code removal

#49 Remove USEMULTINTRINSIC
  jsrc/j.h
  jsrc/u.c
  jsrc/verbs/ve.c
Labels: code removal

#54 Removing even more SYS stuff
  jsrc/f2.c
  jsrc/io.c
  jsrc/j.h
  jsrc/jdlllic.c
  jsrc/js.h
  jsrc/jtype.h
  jsrc/m.h
  jsrc/x15.c
  jsrc/xa.c
  jsrc/xd.c
  jsrc/xf.c
  jsrc/xh.c
  jsrc/xl.c
  jsrc/xo.c
  jsrc/xt.c
Labels: code removal

#59 Remove 2 files
  jsrc/cipfloatmm_t.h
  jsrc/jx_utils_jnative.h
Labels: code removal

#62 Removals & clang-format
  .clang-format
  base64/lib/arch/generic/dec_tail.c
  base64/lib/arch/generic/enc_tail.c
  base64/lib/env.h
  jsrc/tags.txt
Labels: code removal

#63 Remove AES
  jsrc/CMakeLists.txt
  jsrc/aes-arm.c
  jsrc/aes-arm_table.h
  jsrc/aes-c.c
  jsrc/aes-c.h
  jsrc/aes-ni.c
  jsrc/i.c
  jsrc/j.c
  jsrc/je.h
  jsrc/x.c
  jsrc/xaes.c
  test/CMakeLists.txt
  test/g128x7.ijs
Labels: code removal

#64 Decrease test flakiness
  test/tsu.ijs
Labels: ci / build

#67 More folders
  jsrc/CMakeLists.txt
  jsrc/conjunctions/cx.c
  jsrc/debugging/d.c
  jsrc/debugging/d.h
  jsrc/debugging/dc.c
  jsrc/debugging/dss.c
  jsrc/debugging/dstop.c
  jsrc/debugging/dsusp.c
  jsrc/format/f.c
  jsrc/format/f2.c
  jsrc/format/fbu.c
  jsrc/i.c
  jsrc/io.c
  jsrc/parsing/p.c
  jsrc/parsing/p.h
  jsrc/parsing/pv.c
  jsrc/px.c
  jsrc/representations/r.c
  jsrc/representations/rl.c
  jsrc/representations/rt.c
  jsrc/words/w.c
  jsrc/words/w.h
  jsrc/words/wc.c
  jsrc/words/wn.c
  jsrc/words/ws.c
  jsrc/xenos/x.c
  jsrc/xenos/x.h
  jsrc/xenos/x15.c
  jsrc/xenos/xa.c
  jsrc/xenos/xb.c
  jsrc/xenos/xc.c
  jsrc/xenos/xc.h
  jsrc/xenos/xcrc.c
  jsrc/xenos/xd.c
  jsrc/xenos/xf.c
  jsrc/xenos/xfmt.c
  jsrc/xenos/xh.c
  jsrc/xenos/xi.c
  jsrc/xenos/xl.c
  jsrc/xenos/xo.c
  jsrc/xenos/xs.c
  jsrc/xenos/xt.c
  jsrc/xenos/xu.c
  jsrc/xsha.c
Labels: code removal

#66 Remove hostdefs and netdefs
  hostdefs/hostdefs.c
  hostdefs/hostdefs_win32.ijs
  netdefs/netdefs.c
  netdefs/netdefs_win32.ijs
Labels: code removal

#69 Remove blis, gemm etc.
  jsrc/CMakeLists.txt
  jsrc/blis.h
  jsrc/blis/gemm_vec-ref.c
  jsrc/conjunctions/cip.c
  jsrc/cpuinfo.c
  jsrc/cpuinfo.h
  jsrc/gemm.c
  jsrc/gemm.h
  jsrc/i.c
  jsrc/j.c
  jsrc/j.h
  jsrc/je.h
  jsrc/jt.h
  jsrc/m.c
  jsrc/xenos/x.c
  jsrc/xenos/xa.c
  jsrc/xenos/xc.h
  jsrc/xenos/xh.c
  jsrc/xenos/xt.c
Labels: code removal

#73 Remove openmp
  CMakeLists.txt
  base64/lib/lib.c
  base64/lib/lib_openmp.c
  cmake/FindOpenMP.cmake
  jsrc/CMakeLists.txt
  jsrc/j.h
Labels: code removal

#72 Organize headers to folders
  jsrc/conjunctions/cip_t.h
  jsrc/cr_t.h
  jsrc/verbs/crc32c.h
  jsrc/verbs/crc32ctables.h
  jsrc/verbs/vg.h
  jsrc/verbs/vgmerge.h
  jsrc/verbs/vgmergemincomp.h
  jsrc/verbs/vgsort.h
  jsrc/verbs/vgsortq.h
Labels: ci / build, code quality, code removal

#74 Add QtCreator config files to .gitignore
  .gitignore
Labels: ci / build

#75 Added meson build files
  .gitignore
Labels: ci / build

#81 Update LESSONS
  .gitignore
  learning/J_EXAMPLES.md
  learning/LIVESTREAM_LESSONS.md
Labels: documentation

#77 Added -fPIE and -fPIC to compiler flags
  CMakeLists.txt
Labels: ci / build

#78 Porting TALLY (Part 1)
  .clang-format
  docs/REFACTORINGS.md
  jsrc/CMakeLists.txt
  jsrc/j.h
  jsrc/jtype.h
  jsrc/verbs/monadic/tally.cpp
  jsrc/verbs/v.c
Labels: c to c++

#88 Add `set_value_at` & clean up
  jsrc/k.c
  jsrc/verbs/monadic/tally.cpp
  learning/REFACTORINGS.md
Labels: c to c++, code removal

#80 Setting up Doxygen + Breathe + Sphinx
  CMakeLists.txt
  cmake/FindSphinx.cmake
  docs/CMakeLists.txt
  docs/Doxyfile.in
  docs/source/_static/j.jpg
  docs/source/adverbs.rst
  docs/source/conf.py
  docs/source/conjunctions.rst
  docs/source/dyadic.rst
  docs/source/index.rst
  docs/source/monadic.rst
  docs/source/verbs.rst
  jsrc/verbs/monadic/tally.cpp
Labels: ci / build, documentation

#56 Update README.md
  README.md
Labels: documentation

#93 Rename `jttally` to `tally` & conditional documentation build
  CMakeLists.txt
  CONTRIBUTING.md
  docs/source/monadic.rst
  jsrc/CMakeLists.txt
  jsrc/adverbs/ai.c
  jsrc/adverbs/ao.c
  jsrc/adverbs/as.c
  jsrc/ja.h
  jsrc/je.h
  jsrc/t.c
  jsrc/verbs/monadic/tally.cpp
Labels: c to c++, documentation

#95 Removed unused functions and few macros
  CMakeLists.txt
  jsrc/CMakeLists.txt
  jsrc/adverbs/a.h
  jsrc/adverbs/ap.c
  jsrc/adverbs/ar.c
  jsrc/adverbs/au.c
  jsrc/conjunctions/ca.c
  jsrc/conjunctions/cf.c
  jsrc/conjunctions/cp.c
  jsrc/conjunctions/cpdtsp.c
  jsrc/conjunctions/cx.c
  jsrc/debugging/dsusp.c
  jsrc/format/f.c
  jsrc/io.c
  jsrc/ja.h
  jsrc/u.c
  jsrc/verbs/v0.c
  jsrc/verbs/v2.c
  jsrc/verbs/vfft.c
  jsrc/verbs/vsb.c
  jsrc/verbs/vx.c
  jsrc/xenos/xf.c
Labels: code removal
