Repository codereport/jsource, pull requests merged in 2021-03, with the labels that each got.

#195 Removal
  README.md
  jsrc/adverbs/a.h
  jsrc/adverbs/ab.c
  jsrc/adverbs/am.c
  jsrc/adverbs/ao.c
  jsrc/adverbs/ap.c
  jsrc/adverbs/ar.c
  jsrc/adverbs/ar.h
  jsrc/adverbs/as.c
  jsrc/conjunctions/cc.c
  jsrc/conjunctions/cip.c
  jsrc/conjunctions/cr.c
  jsrc/conjunctions/cu.c
  jsrc/fnmatch.c
  jsrc/fnmatch.h
  jsrc/j.h
  jsrc/je.h
  jsrc/m.c
  jsrc/parsing/p.c
  jsrc/result.h
  jsrc/s.c
  jsrc/sl.c
  jsrc/u.c
  jsrc/verbs/dyadic/take_drop.cpp
  jsrc/verbs/v1.c
  jsrc/verbs/va.h
  jsrc/verbs/va1.c
  jsrc/verbs/va2.c
  jsrc/verbs/vasm.h
  jsrc/verbs/vcat.c
  jsrc/verbs/ve.c
  jsrc/verbs/ve.h
  jsrc/verbs/vf.c
  jsrc/verbs/vfrom.c
  jsrc/verbs/vgmerge.h
  jsrc/verbs/vgsort.c
  jsrc/verbs/vgsort.h
  jsrc/verbs/vi.c
  jsrc/verbs/viix.c
  jsrc/verbs/vm.c
  jsrc/verbs/vo.c
  jsrc/words/w.c
  jsrc/xenos/x15.c
Labels: code removal

#194 Fix few disabled tests
  jlibrary/system/util/boot.ijs
  jsrc/adverbs/ar.c
  test/CMakeLists.txt
  test/g18x.ijs
Labels: fix

#193 Doc update and fixes
  CONTRIBUTING.md
  docs/CMakeLists.txt
  docs/source/conf.py
Labels: documentation

#210 Remove underscore from Github link.
  README.md
Labels: documentation

#204 Small cleanup to make_array
  jsrc/array.hpp
Labels: code quality

#202 Add EXCLUDE_FROM_ALL to add_subdirectory(An-Algorithm-Library)
  CMakeLists.txt
Labels: ci / build
