Repository codereport/jsource, pull requests merged in 2021-02, with the labels that each got.

#99 README: adding Java example to Comparison of Languages
  README.md
Labels: documentation

#98 Group unit tests into slow and fast tests
  CONTRIBUTING.md
  test/CMakeLists.txt
Labels: ci / build

#104 Formatting Types in jtype.h
  jsrc/jtype.h
Labels: code quality

#106 Disable flaky gmmf tests
  test/CMakeLists.txt
Labels: ci / build

#108 Enums
  jsrc/jtype.h
Labels: code quality

#109 Turn on compiler errors
  CMakeLists.txt
  jsrc/conjunctions/cc.c
  jsrc/j.h
  jsrc/jc.h
Labels: ci / build

#110 Porting TALLY (Part 2)
  jsrc/CMakeLists.txt
  jsrc/array.hpp
  jsrc/verbs/monadic/tally.cpp
  learning/REFACTORINGS.md
  test/g400.ijs
  test/g421.ijs
Labels: c to c++

#112 Remove `jtshapex`
  jlibrary/system/main/stdlib.ijs
  jsrc/je.h
  jsrc/t.c
  jsrc/verbs/v.c
  learning/REFACTORINGS.md
  test/g210.ijs
Labels: code removal

#114 Remove LEAKSNIFF & friends
  jsrc/je.h
  jsrc/m.c
  jsrc/xenos/x.c
Labels: code removal

#116 Replacing `MC` with `memcpy`
  jsrc/adverbs/a.c
  jsrc/adverbs/ab.c
  jsrc/adverbs/am.c
  jsrc/adverbs/amn.c
  jsrc/adverbs/ao.c
  jsrc/adverbs/ap.c
  jsrc/adverbs/ar.c
  jsrc/adverbs/ar.h
  jsrc/adverbs/as.c
  jsrc/conjunctions/cc.c
  jsrc/conjunctions/cip_t.h
  jsrc/conjunctions/cv.c
  jsrc/conjunctions/cx.c
  jsrc/debugging/d.c
  jsrc/format/f.c
  jsrc/format/f2.c
  jsrc/i.c
  jsrc/io.c
  jsrc/j.h
  jsrc/ja.h
  jsrc/jdlllic.c
  jsrc/k.c
  jsrc/m.c
  jsrc/representations/r.c
  jsrc/representations/rl.c
  jsrc/representations/rt.c
  jsrc/s.c
  jsrc/sn.c
  jsrc/u.c
  jsrc/verbs/v.c
  jsrc/verbs/v0.c
  jsrc/verbs/v2.c
  jsrc/verbs/va2s.c
  jsrc/verbs/vb.c
  jsrc/verbs/vcant.c
  jsrc/verbs/vcat.c
  jsrc/verbs/vd.c
  jsrc/verbs/ve.c
  jsrc/verbs/vf.c
  jsrc/verbs/vfrom.c
  jsrc/verbs/vfromsp.c
  jsrc/verbs/vgsort.c
  jsrc/verbs/vi.c
  jsrc/verbs/vm.c
  jsrc/verbs/vo.c
  jsrc/verbs/vrep.c
  jsrc/verbs/vs.c
  jsrc/verbs/vsb.c
  jsrc/verbs/vt.c
  jsrc/vu.c
  jsrc/words/w.c
  jsrc/words/wn.c
  jsrc/xenos/x15.c
  jsrc/xenos/xa.c
  jsrc/xenos/xb.c
  jsrc/xenos/xf.c
  jsrc/xenos/xfmt.c
  jsrc/xenos/xh.c
  jsrc/xenos/xo.c
  jsrc/xenos/xt.c
Labels: c to c++

#118 Misc removals
  CMakeLists.txt
  jsrc/adverbs/ao.c
  jsrc/dtoa.c
  jsrc/j.h
  jsrc/k.c
  jsrc/m.c
  jsrc/parsing/p.c
  jsrc/verbs/vg.c
  jsrc/verbs/vgsort.c
  jsrc/verbs/vgsortq.h
  jsrc/verbs/vsb.c
Labels: code removal

#119 Removing `jtlog*`
  jsrc/je.h
  jsrc/verbs/vm.c
  jsrc/verbs/vx.c
  test/gq201.ijs
Labels: code removal

#121 Cleaning up .rst files
  docs/source/dyadic.rst
  docs/source/monadic.rst
  docs/source/verbs.rst
  jsrc/verbs/monadic/tally.cpp
Labels: documentation

#113 Port SHAPE
  .clang-format
  docs/source/monadic.rst
  docs/source/verbs.rst
  jsrc/CMakeLists.txt
  jsrc/adverbs/am.c
  jsrc/adverbs/am1.c
  jsrc/adverbs/amn.c
  jsrc/adverbs/ap.c
  jsrc/adverbs/ar.c
  jsrc/adverbs/as.c
  jsrc/array.hpp
  jsrc/conjunctions/cc.c
  jsrc/conjunctions/cg.c
  jsrc/conjunctions/cp.c
  jsrc/format/f.c
  jsrc/interpreter_utilities.hpp
  jsrc/j.h
  jsrc/ja.h
  jsrc/je.h
  jsrc/representations/rl.c
  jsrc/t.c
  jsrc/u.c
  jsrc/verbs/monadic/shape.cpp
  jsrc/verbs/monadic/tally.cpp
  jsrc/verbs/v.c
  jsrc/verbs/v2.c
  jsrc/verbs/vb.c
  jsrc/verbs/vcat.c
  jsrc/verbs/vd.c
  jsrc/verbs/ve.c
  jsrc/verbs/vf.c
  jsrc/verbs/vfrom.c
  jsrc/verbs/vg.c
  jsrc/verbs/vi.c
  jsrc/verbs/vrand.c
  jsrc/verbs/vs.c
  jsrc/verbs/vt.c
  jsrc/xenos/xfmt.c
  learning/REFACTORINGS.md
Labels: c to c++

#122 Port RANK
  docs/source/monadic.rst
  docs/source/verbs.rst
  jsrc/CMakeLists.txt
  jsrc/array.hpp
  jsrc/conjunctions/ca.c
  jsrc/conjunctions/cf.c
  jsrc/je.h
  jsrc/verbs/monadic/rank.cpp
  jsrc/verbs/monadic/shape.cpp
  jsrc/verbs/v.c
  learning/REFACTORINGS.md
Labels: c to c++

#123 Reduce compiler warnings / remove dead code
  jsrc/dtoa.c
Labels: code removal

#134 Remove some conditional compilation
  jsrc/CMakeLists.txt
  jsrc/adverbs/au.c
  jsrc/conjunctions/cu.c
  jsrc/debugging/dsusp.c
  jsrc/dtoa.c
  jsrc/dtoa.h
  jsrc/fnmatch.c
  jsrc/i.c
  jsrc/io.c
  jsrc/j.h
  jsrc/ja.h
  jsrc/jconsole.c
  jsrc/je.h
  jsrc/jep.c
  jsrc/js.h
  jsrc/jt.h
  jsrc/linenoise.c
  jsrc/linenoise.h
  jsrc/m.c
  jsrc/parsing/p.c
  jsrc/sc.c
  jsrc/verbs/vfrom.c
  jsrc/verbs/vgmerge.h
  jsrc/verbs/vi.c
  jsrc/verbs/vo.c
  jsrc/words/wn.c
  jsrc/xenos/xs.c
  jsrc/xenos/xt.c
  test/tsu.ijs
Labels: code removal

#131 Fix compiling in GCC 8+ -Wno-cast-function-type
  CMakeLists.txt
Labels: ci / build

#128 Removing XNUM functions
  jsrc/conjunctions/cx.c
  jsrc/io.c
  jsrc/ja.h
  jsrc/je.h
  jsrc/verbs/v2.c
  jsrc/verbs/va1.c
  jsrc/verbs/va2.c
  jsrc/verbs/ve.h
  jsrc/verbs/vfrom.c
  jsrc/verbs/vm.c
  jsrc/verbs/vq.c
  jsrc/verbs/vx.c
  jsrc/vx.h
  jsrc/words/wn.c
  test/g410.ijs
  test/gnan.ijs
  test/gpco2.ijs
  test/gpdd.ijs
  test/gq.ijs
  test/gq201.ijs
  test/gqco.ijs
  test/gqnonrat.ijs
  test/gx132.ijs
  test/gxco.ijs
  test/gxco1.ijs
  test/gxco2.ijs
  test/gxinf.ijs
Labels: code removal

#137 Remove some non-portable headers
  jsrc/fnmatch.h
  jsrc/io.c
  jsrc/j.h
  jsrc/jconsole.c
  jsrc/jt.h
  jsrc/xenos/x.c
  jsrc/xenos/x15.c
  jsrc/xenos/xd.c
  jsrc/xenos/xf.c
  jsrc/xenos/xl.c
Labels: code quality, code removal

#139 Fix build for mac
  jsrc/jconsole.c
  jsrc/verbs/vfrom.c
Labels: ci / build

#140 Remove __LP64__ and crc* files + more
  jsrc/CMakeLists.txt
  jsrc/conjunctions/ca.c
  jsrc/j.h
  jsrc/ja.h
  jsrc/verbs/crc32c.c
  jsrc/verbs/crc32c.h
  jsrc/verbs/crc32ctables.h
  jsrc/verbs/monadic/rank.cpp
  jsrc/verbs/monadic/shape.cpp
  jsrc/verbs/monadic/tally.cpp
  test/g200.ijs
  test/gxco1.ijs
Labels: code removal

#142 Porting RIGHT
  docs/source/verbs.rst
  jsrc/CMakeLists.txt
  jsrc/je.h
  jsrc/t.c
  jsrc/verbs/monadic/same.cpp
  jsrc/verbs/v.c
Labels: c to c++

#143 Update gitignore
  .gitignore
Labels: ci / build

#144 Add p.ijs
  jlibrary/system/util/boot.ijs
  jlibrary/system/util/p.ijs
Labels: ci / build

#145 `ut` for quickly running unit tests
  jlibrary/system/util/p.ijs
Labels: ci / build

#146 Remove xnum support from roll & deal
  jsrc/ja.h
  jsrc/verbs/vrand.c
  test/g128x5.ijs
  test/g300.ijs
  test/g3x.ijs
  test/g400.ijs
  test/g401.ijs
  test/g601.ijs
  test/gmnom.ijs
  test/gnan.ijs
  test/gpco2.ijs
  test/gqco.ijs
  test/gsco2.ijs
  test/gsco2u.ijs
  test/gsco2w.ijs
Labels: code removal

#150 Remove compiler conditional on OVF
  jsrc/verbs/vasm.h
Labels: code removal

#149 Remove references to architecture specific code in Base64 library
  base64/CMakeLists.txt
  base64/include/libbase64.h
  base64/lib/arch/generic/64/enc_loop.c
  base64/lib/arch/generic/codec-generic.c
  base64/lib/arch/generic/dec_head.c
  base64/lib/arch/generic/dec_tail.c
  base64/lib/arch/generic/enc_head.c
  base64/lib/arch/generic/enc_tail.c
  base64/lib/codec.c
  base64/lib/codec.h
  base64/lib/codec_choose.c
  base64/lib/codecs.h
  base64/lib/lib.c
  jsrc/xenos/xcrc.c
Labels: code removal

#151 More cleanups in the base64 code
  base64/CMakeLists.txt
  base64/include/libbase64.h
  base64/lib/codec.c
  base64/lib/codec.h
  base64/lib/env.h
  base64/lib/lib.c
  base64/lib/tables/table_dec_32bit.h
  base64/lib/tables/table_enc_12bit.h
  base64/lib/tables/tables.c
  base64/lib/tables/tables.h
Labels: code removal

#152 Remove unused base64 constants from xenos file
  jsrc/xenos/xcrc.c
Labels: code removal

#153 Clang-format the base64 library
  base64/include/libbase64.h
  base64/lib/codec.c
  base64/lib/codec.h
  base64/lib/lib.c
  base64/lib/tables/tables.c
  base64/lib/tables/tables.h
Labels: c to c++

#129 write markdown tables in RST file
  docs/.gitignore
  docs/CMakeLists.txt
  docs/scripts/preprocessor.py
  docs/source/verbs.rst
Labels: ci / build

#154 Remove unused functions
  jsrc/CMakeLists.txt
  jsrc/adverbs/au.c
  jsrc/conjunctions/ch.c
  jsrc/conjunctions/cu.c
  jsrc/debugging/dsusp.c
  jsrc/jdlllic.c
  jsrc/je.h
  jsrc/m.c
  jsrc/px.c
  jsrc/u.c
  jsrc/verbs/vrand.c
  jsrc/xenos/x15.c
  jsrc/xenos/xa.c
  jsrc/xenos/xb.c
  jsrc/xenos/xc.c
  jsrc/xenos/xi.c
  jsrc/xenos/xl.c
  jsrc/xenos/xu.c
Labels: code removal

#156 Delete TABLES from docs
  docs/source/verbs.rst
Labels: code removal, documentation

#157 Port TAKE & DROP (Part 1)
  jsrc/CMakeLists.txt
  jsrc/verbs/dyadic/take_drop.cpp
  learning/LIVESTREAM_LESSONS.md
  learning/REFACTORINGS.md
Labels: c to c++

#159 removed fixed path.
  docs/source/conf.py
Labels: documentation

#160 Use correct variable name in TODO message
  jsrc/verbs/dyadic/take_drop.cpp
Labels: documentation

#161 Remove unused macro two_to_the_31
  jsrc/verbs/vrand.c
Labels: code removal

#165 Removing unused functions and dead code
  jsrc/conjunctions/cg.c
  jsrc/conjunctions/cr.c
  jsrc/j.h
  jsrc/ja.h
  jsrc/jdlllic.c
  jsrc/je.h
  jsrc/verbs/v.c
  jsrc/verbs/v1.c
  jsrc/verbs/ve.c
  jsrc/verbs/ve.h
  jsrc/verbs/vf.c
  jsrc/verbs/vg.h
  jsrc/verbs/viix.c
  jsrc/verbs/vo.c
  jsrc/verbs/vz.c
  jsrc/vz.h
  jsrc/xenos/x.c
  jsrc/xenos/xl.c
  jsrc/xenos/xu.c
Labels: code removal

#167 Get rid of macros MALLOC and FREE
  jsrc/io.c
  jsrc/m.c
  jsrc/m.h
  jsrc/xenos/x15.c
Labels: code removal

#168 Cleanup dtoa.c
  jsrc/dtoa.c
  jsrc/dtoa.h
Labels: code removal

#171 Remove extended complex & floating point
  jsrc/format/f.c
  jsrc/j.c
  jsrc/jtype.h
  jsrc/k.c
  jsrc/m.c
  jsrc/verbs/vf.c
Labels: code removal

#174 Remove targ from documentation of item_count in array.hpp
  jsrc/array.hpp
Labels: documentation

#176 Add Ruby example to code snippets
  README.md
Labels: documentation

#173 Simplify code regarding jtjinit
  jsrc/i.c
  jsrc/io.c
  jsrc/je.h
Labels: code quality

#177 Fix example of Pi calculation
  learning/J_EXAMPLES.md
Labels: documentation

#181 Remove FHS from C source
  jsrc/jeload.cpp
Labels: code removal

#180 Remove GETPROCADDRESS macro
  jsrc/jconsole.c
Labels: code removal

#179 Add link to E.12 on refactorings page
  learning/REFACTORINGS.md
Labels: documentation

#182 Move len variable in jeload.cpp
  jsrc/jeload.cpp
Labels: code quality

#185 Remove few macros
  jsrc/adverbs/ar.c
  jsrc/adverbs/as.c
  jsrc/conjunctions/cr.c
  jsrc/j.h
  jsrc/ja.h
  jsrc/m.c
  jsrc/verbs/dyadic/take_drop.cpp
  jsrc/verbs/v.c
  jsrc/verbs/vcat.c
  jsrc/verbs/vf.c
  jsrc/verbs/vfrom.c
  jsrc/verbs/vi.c
  jsrc/verbs/vs.c
  jsrc/words/w.c
Labels: code quality, code removal

#187 Adding `algorithm.hpp` with `zip_find`, `zip_found` & `is_mismatched`
  jsrc/CMakeLists.txt
  jsrc/algorithm.hpp
  jsrc/verbs/dyadic/take_drop.cpp
  learning/LIVESTREAM_LESSONS.md
Labels: c to c++

#188 Clang-format & cleanup
  jsrc/algorithm.hpp
  jsrc/verbs/dyadic/take_drop.cpp
  learning/LIVESTREAM_LESSONS.md
Labels: code quality

#190 Enable use of newer compiler version
  CMakeLists.txt
Labels: ci / build

#189 Add some more functions to algorithm.hpp
  jsrc/algorithm.hpp
  jsrc/verbs/dyadic/take_drop.cpp
Labels: enhancement
